
#pragma once 

// MATRIX
#define MATRIX_COLS 1
#define MATRIX_ROWS 5

// PINS
#define MATRIX_ROW_PINS {A10, A8, A3, A2, A1}

#define DISCHARGE_PIN A4

#define ANALOG_READINGS_INPUT A7

// NUMBERS
#define DISCHARGE_TIME_US 10

#define NOISE_THRESHOLD_SAMPLING_COUNT 40
#define NOISE_OFFSET 50

#define ACTUATION_LEVEL 500
#define RELEASE_LEVEL 450

#define DEFAULT_ACTUATION_LEVEL 500
#define DEFAULT_RELEASE_LEVEL 450
#define DEFAULT_CEILING_LEVEL 1023
#define DEFAULT_CONSOLE_LOG_STATUS false
#define DEFAULT_CALIBRATION_STATUS false

#define EECONFIG_KB_DATA_SIZE 128